Repository CSC4790-Fall2023-Org/senior-project-middle-management, pull requests merged in 2023-12, with the labels that each got.

#303 round hours
  src/main/frontend/components/ShiftCard.js
  src/main/frontend/components/company-dashboard-components/AddEmployeeBody.js
Labels: bug, frontend, sprint three

#305 delete shifts
  src/main/java/com/ems/Utils/ShiftUtils.java
  src/main/java/com/ems/controllers/ShiftController.java
  src/main/java/com/ems/services/DatabaseServices.java
  src/main/java/com/ems/services/ShiftServices.java
Labels: api

#308 get org info
  src/main/java/com/ems/Utils/ResponseUtils.java
  src/main/java/com/ems/builders/JSONObjectBuilder.java
  src/main/java/com/ems/controllers/OrganizationController.java
  src/main/java/com/ems/services/OrganizationServices.java
Labels: api

#310 get employee info
  src/main/java/com/ems/Utils/ResponseUtils.java
  src/main/java/com/ems/builders/JSONObjectBuilder.java
  src/main/java/com/ems/controllers/EmployeeController.java
  src/main/java/com/ems/services/EmployeeServices.java
Labels: api

#309 Complete Transfer
  src/main/frontend/components/MyShiftCardSwipe.js
  src/main/frontend/components/MyShiftList.js
  src/main/frontend/components/TransferShiftCardSwipe.js
  src/main/frontend/components/TransferShiftList.js
  src/main/frontend/components/TransferShiftModal.js
  src/main/frontend/components/manager-dashboard-components/AddShiftBody.js
Labels: api, frontend, sprint three

#313 load data
  src/main/frontend/components/ProfileSettingsContainer.js
Labels: api

#314 render company info
  src/main/frontend/components/company-dashboard-components/CompanyInfoDashboard.js
  src/main/frontend/components/company-dashboard-components/CompanyLocationsModal.js
  src/main/frontend/components/company-dashboard-components/LocationCard.js
Labels: api
